# Location of top-level MicroPython directory
MPY_DIR = ../libs/micropython

# Name of module
MOD = rainbowio

# Source files (.c or .py)
SRC = rainbowio.c

# Architecture to build for (x86, x64, armv7m, xtensa, xtensawin)
ARCH = x64

# Include to get the rules for compiling and linking the module
include $(MPY_DIR)/py/dynruntime.mk